/*
 Copyright (c) 2026 Ashraf Morningstar
 These are personal recreations of existing projects, developed by Ashraf Morningstar
 for learning and skill development.
 Original project concepts remain the intellectual property of their respective creators.
 Repository: https://github.com/AshrafMorningstar
*/

version: "3.8"

services:
  webdev-portfolio:
    image: ashrafmorningstar/webdev-roadmap
    build: .
    ports:
      - "8080:80"
    restart: always
    container_name: webdev-portfolio-container
